spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    url: ${RDS_HOST}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  jwt:
    secret:
      key: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      accessKey: ${ACCESS_KEY_ID}
      secretKey: ${ACCESS_KEY_SECRET}
    region:
      static: ${REGION}
      auto: false
