spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    url: ${RDS_HOST}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  jwt:
    secret:
      key: ${JWT_SECRET_KEY}
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
cloud:
  aws:
    s3:
      bucket: asdfasdfa
    credentials:
      accessKey: teasdfsaf
      secretKey: asdfasdf
    region:
      static: asdfasdf
      auto: false
